import { Open_Sans, Cormorant_Garamond } from "next/font/google";
import "@/assets/main.scss";

const openSans =  Open_Sans({
  variable: "--font-open-sans",
  subsets: ["cyrillic"],
});

const cormorantGaramondMono = Cormorant_Garamond({
  variable: "--font-cormorant_garamond",
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={`${openSans.variable} ${cormorantGaramondMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
